Repository nu-radio/NuRadioMC, pull requests merged in 2025-09, with the labels that each got.

#977 Raise `ValueError` if if new arguments to Singleton `__init__` would be ignored
  NuRadioReco/detector/detector_base.py
  NuRadioReco/utilities/metaclasses.py
Labels: Core/Framework, cleanup

#972 PR test: increased simulated/triggered events to reduce errors in PR tests
  NuRadioMC/SignalProp/examples/birefringence_examples/06_Veff_comparison/06_A_generate_event_list.py
  NuRadioMC/SignalProp/examples/birefringence_examples/06_Veff_comparison/config_birefringence.yaml
  NuRadioMC/SignalProp/examples/birefringence_examples/06_Veff_comparison/config_no_birefringence.yaml
  NuRadioMC/examples/01_Veff_simulation/T01generate_event_list.py
  NuRadioMC/examples/06_webinar/W01_create_input.py
  NuRadioMC/test/examples/test_veff_example.sh
  NuRadioMC/test/examples/test_webinar.sh
Labels: Bug, Documentation/CI/Examples

#984 Hotfix: correct specification of pygdsm / galacticnoise version requirements.
  .github/workflows/run_tests.yaml
  pyproject.toml
Labels: Bug

#962 Example of how to add thermal noise to simulation events
  NuRadioReco/examples/RNOG/thermal_noise/eff_temperatures/eff_temperature_-1.0m_ntheta100_GL3.json
  NuRadioReco/examples/RNOG/thermal_noise/eff_temperatures/eff_temperature_-100m_ntheta100.json
  NuRadioReco/examples/RNOG/thermal_noise/eff_temperatures/eff_temperature_-100m_ntheta100_GL3.json
  NuRadioReco/examples/RNOG/thermal_noise/eff_temperatures/eff_temperature_-2.0m_ntheta100_GL3.json
  NuRadioReco/examples/RNOG/thermal_noise/eff_temperatures/eff_temperature_-3.0m_ntheta100_GL3.json
  NuRadioReco/examples/RNOG/thermal_noise/eff_temperatures/eff_temperature_-40m_ntheta100.json
  NuRadioReco/examples/RNOG/thermal_noise/generate_thermal_noise.ipynb
Labels: Documentation/CI/Examples

#990 Fix get_index_of_refraction() at z_air_boundary
  NuRadioMC/utilities/medium_base.py
  changelog.txt
Labels: Bug
